// GENERATED by dart_cpp_bridge codegen — do not edit.
// ignore_for_file: unused_element, unused_import

import 'dart:async';
import 'dart:typed_data';

import 'package:dart_cpp_bridge/dart_cpp_bridge.dart';

/// Wire-level API singleton. Access via [BridgeApiImpl.instance].
final class BridgeApiImpl {
  BridgeApiImpl._(this.bridge);

  final DartCppBridge bridge;

  // ── Singleton ──
  static BridgeApiImpl? _instance;
  static BridgeApiImpl get instance {
    final i = _instance;
    if (i == null) throw StateError('DcbLib.init() must be called first');
    return i;
  }

  static void initSingleton(DartCppBridge bridge) =>
      _instance = BridgeApiImpl._(bridge);
  static void disposeSingleton() => _instance = null;

  static const int startUvWorkerId = 18716410;
  static const int callDartFromUvId = 201331851;
  static const int testCbridgeInvokeId = 300843582;
  static const int uvComputeId = 460040803;
  static const int testChannelServiceConcurrentId = 595582421;
  static const int uvStreamId = 828415216;
  static const int testCbridgeAsyncFailId = 1096234678;
  static const int testChannelServiceId = 1620642776;
  static const int testCbridgeAsyncId = 1657238865;
  static const int askUvId = 2040169010;
  static const int stopUvWorkerId = 2048427889;
  static const int testCbridgeAsyncCancelId = 2117983701;

  Future<String> startUvWorker() async {
    final _payload = ByteWriter();
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(
      startUvWorkerId,
      _payloadBytes,
    );
    return ByteReader(_bytes).str();
  }

  Future<String> callDartFromUv(
    Future<String> Function(String) callback,
    String input,
  ) async {
    final _callbackWrapper = (Uint8List _argBytes) async {
      final _r = ByteReader(_argBytes);
      final _a0 = _r.str();
      final _res = await callback(_a0);
      final _w = ByteWriter();
      _w.str(_res);
      return _w.takeBytes();
    };
    final _callbackId = bridge.registerDartFn(_callbackWrapper);
    try {
      final _payload = ByteWriter();
      _payload.u64(_callbackId);
      _payload.str(input);
      final _payloadBytes = _payload.takeBytes();
      final _bytes = await bridge.invokeAsyncMethod(
        callDartFromUvId,
        _payloadBytes,
      );
      return ByteReader(_bytes).str();
    } finally {
      bridge.unregisterDartFn(_callbackId);
    }
  }

  Future<String> testCbridgeInvoke(
    Future<String> Function(String) callback,
    String input,
  ) async {
    final _callbackWrapper = (Uint8List _argBytes) async {
      final _r = ByteReader(_argBytes);
      final _a0 = _r.str();
      final _res = await callback(_a0);
      final _w = ByteWriter();
      _w.str(_res);
      return _w.takeBytes();
    };
    final _callbackId = bridge.registerDartFn(_callbackWrapper);
    try {
      final _payload = ByteWriter();
      _payload.u64(_callbackId);
      _payload.str(input);
      final _payloadBytes = _payload.takeBytes();
      final _bytes = await bridge.invokeAsyncMethod(
        testCbridgeInvokeId,
        _payloadBytes,
      );
      return ByteReader(_bytes).str();
    } finally {
      bridge.unregisterDartFn(_callbackId);
    }
  }

  Future<int> uvCompute(int n) async {
    final _payload = ByteWriter();
    _payload.i32(n);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(uvComputeId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  Future<String> testChannelServiceConcurrent() async {
    final _payload = ByteWriter();
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(
      testChannelServiceConcurrentId,
      _payloadBytes,
    );
    return ByteReader(_bytes).str();
  }

  Stream<String> uvStream(int count, int intervalMs) {
    final _payload = ByteWriter();
    _payload.i32(count);
    _payload.i32(intervalMs);
    return bridge.openStream<String>(
      uvStreamId,
      _payload.takeBytes(),
      (final _r) => _r.str(),
    );
  }

  Future<String> testCbridgeAsyncFail() async {
    final _payload = ByteWriter();
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(
      testCbridgeAsyncFailId,
      _payloadBytes,
    );
    return ByteReader(_bytes).str();
  }

  Future<String> testChannelService() async {
    final _payload = ByteWriter();
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(
      testChannelServiceId,
      _payloadBytes,
    );
    return ByteReader(_bytes).str();
  }

  Future<String> testCbridgeAsync() async {
    final _payload = ByteWriter();
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(
      testCbridgeAsyncId,
      _payloadBytes,
    );
    return ByteReader(_bytes).str();
  }

  Future<String> askUv(String message) async {
    final _payload = ByteWriter();
    _payload.str(message);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(askUvId, _payloadBytes);
    return ByteReader(_bytes).str();
  }

  Future<String> stopUvWorker() async {
    final _payload = ByteWriter();
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(
      stopUvWorkerId,
      _payloadBytes,
    );
    return ByteReader(_bytes).str();
  }

  Future<String> testCbridgeAsyncCancel() async {
    final _payload = ByteWriter();
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(
      testCbridgeAsyncCancelId,
      _payloadBytes,
    );
    return ByteReader(_bytes).str();
  }
}
