// GENERATED by dart_cpp_bridge codegen — do not edit.
// ignore_for_file: unused_element, unused_import

import 'dart:async';
import 'dart:typed_data';

import 'package:dart_cpp_bridge/dart_cpp_bridge.dart';



/// Wire-level API singleton. Access via [BridgeApiImpl.instance].
final class BridgeApiImpl {
  BridgeApiImpl._(this.bridge);

  final DartCppBridge bridge;

  // ── Singleton ──
  static BridgeApiImpl? _instance;
  static BridgeApiImpl get instance {
    final i = _instance;
    if (i == null) throw StateError('DcbLib.init() must be called first');
    return i;
  }
  static void initSingleton(DartCppBridge bridge) => _instance = BridgeApiImpl._(bridge);
  static void disposeSingleton() => _instance = null;

  static const int startUvWorkerId = 18716410;
  static const int uvComputeId = 460040803;
  static const int uvStreamId = 828415216;
  static const int askUvId = 2040169010;
  static const int stopUvWorkerId = 2048427889;

  Future<String> startUvWorker() async {
    final _payload = ByteWriter();
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(startUvWorkerId, _payloadBytes);
    return ByteReader(_bytes).str();
  }

  Future<int> uvCompute(int n) async {
    final _payload = ByteWriter();
    _payload.i32(n);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(uvComputeId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  Stream<String> uvStream(int count, int intervalMs) {
    final _payload = ByteWriter();
    _payload.i32(count);
    _payload.i32(intervalMs);
    return bridge.openStream<String>(uvStreamId, _payload.takeBytes(), (final _r) => _r.str());
  }

  Future<String> askUv(String message) async {
    final _payload = ByteWriter();
    _payload.str(message);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(askUvId, _payloadBytes);
    return ByteReader(_bytes).str();
  }

  Future<String> stopUvWorker() async {
    final _payload = ByteWriter();
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(stopUvWorkerId, _payloadBytes);
    return ByteReader(_bytes).str();
  }
}
