// multi_runtime_api.cpp — Business implementation for multi-runtime demo.
//
// Architecture:
//   Main Runtime (dcb::Runtime, io thread) ← Dart talks to this
//     ↕ co::oneshot / co::mpsc channels (non-blocking send, coroutine recv)
//   Worker A ("processor") — own io_context + thread
//   Worker B ("responder") — own io_context + thread
//
// The wire dispatch is auto-generated by codegen. This file only contains
// the business logic: spawning coroutines on workers and communicating
// via channels.

#include "multi_runtime_api.h"

#include "../worker_runtime.hpp"

#include "dart_cpp_bridge/channel.hpp"
#include "dart_cpp_bridge/runtime.hpp"
#include "dart_cpp_bridge/stream_sink.hpp"

#include <atomic>
#include <chrono>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <utility>

namespace multi_rt::api {

namespace {

std::mutex g_mu;
std::unique_ptr<WorkerRuntime> g_worker_a;
std::unique_ptr<WorkerRuntime> g_worker_b;
std::atomic<std::uint32_t> g_ping_counter{0};

}  // namespace

async_simple::coro::Lazy<std::string> start_workers() {
  std::lock_guard lock(g_mu);
  if (!g_worker_a) {
    g_worker_a = std::make_unique<WorkerRuntime>("processor");
    g_worker_a->start();
  }
  if (!g_worker_b) {
    g_worker_b = std::make_unique<WorkerRuntime>("responder");
    g_worker_b->start();
  }
  co_return std::string("workers started");
}

async_simple::coro::Lazy<std::string> stop_workers() {
  std::lock_guard lock(g_mu);
  if (g_worker_a) g_worker_a->stop();
  if (g_worker_b) g_worker_b->stop();
  g_worker_a.reset();
  g_worker_b.reset();
  co_return std::string("workers stopped");
}

async_simple::coro::Lazy<std::string> process_message(std::string message) {
  auto [tx, rx] = co::oneshot::channel<std::string>();

  {
    std::lock_guard lock(g_mu);
    if (!g_worker_a || !g_worker_a->running()) {
      throw std::runtime_error("worker A not running");
    }
    g_worker_a->spawn([tx = std::move(tx), msg = std::move(message)]() mutable
                      -> async_simple::coro::Lazy<> {
      // Runs on Worker A's event loop thread.
      std::string result = "[A:" + msg + "]";
      tx.send(std::move(result));  // non-blocking send back to Main
      co_return;
    });
  }

  // Await Worker A's reply (suspends coroutine, doesn't block thread).
  auto reply = co_await rx.recv();
  if (!reply) {
    throw std::runtime_error("worker A dropped");
  }
  co_return *reply;
}

async_simple::coro::Lazy<std::string> ping_worker(std::string payload) {
  auto [tx, rx] = co::oneshot::channel<std::string>();

  {
    std::lock_guard lock(g_mu);
    if (!g_worker_b || !g_worker_b->running()) {
      throw std::runtime_error("worker B not running");
    }
    auto id = g_ping_counter.fetch_add(1, std::memory_order_relaxed);
    g_worker_b->spawn([tx = std::move(tx), payload = std::move(payload), id]() mutable
                      -> async_simple::coro::Lazy<> {
      // Runs on Worker B's event loop thread.
      std::string result = "[B#" + std::to_string(id) + ":" + payload + "]";
      tx.send(std::move(result));
      co_return;
    });
  }

  auto reply = co_await rx.recv();
  if (!reply) {
    throw std::runtime_error("worker B dropped");
  }
  co_return *reply;
}

async_simple::coro::Lazy<std::string> pipeline(std::string message) {
  // Final reply channel (Worker B → Main).
  auto [tx_final, rx_final] = co::oneshot::channel<std::string>();
  // Intermediate channel (Worker A → Worker B).
  auto [tx_ab, rx_ab] = co::oneshot::channel<std::string>();

  {
    std::lock_guard lock(g_mu);
    if (!g_worker_a || !g_worker_a->running() ||
        !g_worker_b || !g_worker_b->running()) {
      throw std::runtime_error("workers not running");
    }

    // Stage 1: Worker A processes and sends to Worker B.
    g_worker_a->spawn([tx_ab = std::move(tx_ab), msg = std::move(message)]() mutable
                      -> async_simple::coro::Lazy<> {
      std::string stage1 = "A{" + msg + "}";
      tx_ab.send(std::move(stage1));
      co_return;
    });

    // Stage 2: Worker B awaits A's output, processes, sends final.
    g_worker_b->spawn([rx_ab = std::move(rx_ab), tx_final = std::move(tx_final)]() mutable
                      -> async_simple::coro::Lazy<> {
      auto from_a = co_await rx_ab.recv();
      if (!from_a) {
        tx_final.send(std::string("pipeline: A dropped"));
        co_return;
      }
      std::string stage2 = "B[" + *from_a + "]";
      tx_final.send(std::move(stage2));
      co_return;
    });
  }

  // Await final result.
  auto reply = co_await rx_final.recv();
  co_return reply.value_or("pipeline: lost");
}

async_simple::coro::Lazy<std::pair<std::string, std::string>> fan_out(
    std::string message) {
  auto [tx_a, rx_a] = co::oneshot::channel<std::string>();
  auto [tx_b, rx_b] = co::oneshot::channel<std::string>();

  {
    std::lock_guard lock(g_mu);
    if (!g_worker_a || !g_worker_a->running() ||
        !g_worker_b || !g_worker_b->running()) {
      throw std::runtime_error("workers not running");
    }

    g_worker_a->spawn([tx = std::move(tx_a), msg = message]() mutable
                      -> async_simple::coro::Lazy<> {
      tx.send("A:" + msg);
      co_return;
    });

    g_worker_b->spawn([tx = std::move(tx_b), msg = std::move(message)]() mutable
                      -> async_simple::coro::Lazy<> {
      tx.send("B:" + msg);
      co_return;
    });
  }

  // Await both replies (workers run in parallel).
  auto a = co_await rx_a.recv();
  auto b = co_await rx_b.recv();
  co_return std::make_pair(a.value_or("A:lost"), b.value_or("B:lost"));
}

void worker_stream(dcb::StreamSink<std::string> sink, std::int32_t count,
                   std::int32_t interval_ms) {
  // mpsc channel: Worker A (producer) → Main coroutine (consumer → Dart stream).
  auto [tx, rx] = co::mpsc::unbounded<std::string>();

  {
    std::lock_guard lock(g_mu);
    if (!g_worker_a || !g_worker_a->running()) {
      sink.error("worker A not running");
      return;
    }

    // Worker A: emit items with delay.
    g_worker_a->spawn([tx = std::move(tx), count, interval_ms]() mutable
                      -> async_simple::coro::Lazy<> {
      for (std::int32_t i = 0; i < count; ++i) {
        if (interval_ms > 0) {
          std::this_thread::sleep_for(std::chrono::milliseconds(interval_ms));
        }
        if (!tx.send("item_" + std::to_string(i))) {
          break;  // receiver gone
        }
      }
      // tx dropped here → channel closes → recv returns nullopt
      co_return;
    });
  }

  // Spawn a coroutine on Main runtime to consume mpsc and forward to sink.
  // co_await rx.recv() suspends the coroutine (not the thread) until data arrives.
  dcb::Runtime::instance().spawn_on_asio(
      [sink = std::move(sink), rx = std::move(rx)]() mutable
      -> async_simple::coro::Lazy<> {
        while (true) {
          auto item = co_await rx.recv();
          if (!item) break;  // channel closed
          sink.add(*item);
        }
        sink.end();
        co_return;
      });
}

}  // namespace multi_rt::api
