// Stub for codegen parsing only — the real header is generated by stdexec's
// CMake from asio_config.hpp.in. Codegen only needs the standalone-asio
// configuration to resolve asio_executor.hpp (no <asio.hpp> include: the
// full asio header is heavy and irrelevant for parsing API headers).
#pragma once

#define STDEXEC_ASIO_USES_STANDALONE 1
#define STDEXEC_ASIO_USES_BOOST 0

#define ASIOEXEC_ASIO_NAMESPACE asio

#include <system_error>

namespace experimental::execution::asio {
namespace asio_impl = ::asio;
using error_code = std::error_code;
using error_condition = std::error_condition;
namespace errc = std::errc;
using system_error = std::system_error;
}  // namespace experimental::execution::asio

namespace exec = experimental::execution;
