// multi_runtime_api.cpp — Business implementation for multi-runtime demo.
//
// Architecture:
//   Main Runtime (dcb::Runtime, io thread) ← Dart talks to this
//     ↕ co::oneshot / co::mpsc channels (non-blocking send, coroutine recv)
//   Worker A ("processor") — own io_context + thread
//   Worker B ("responder") — own io_context + thread
//
// The wire dispatch is auto-generated by codegen. This file only contains
// the business logic: spawning coroutines on workers and communicating
// via channels.
//
// Coroutines are static exec::task functions (MSVC 19.51 coroutine-lambda
// capture bug, see docs/known_issues.md ID-009); WorkerRuntime::spawn
// launches them with starts_on(worker_scheduler, ...), so co_await resuming
// back to the worker loop is handled by exec::task.

#include "multi_runtime_api.h"

#include "worker_runtime.hpp"

#include "dart_cpp_bridge/channel.hpp"
#include "dart_cpp_bridge/dart_fn.hpp"
#include "dart_cpp_bridge/runtime.hpp"
#include "dart_cpp_bridge/stream_sink.hpp"

#include <stdexec/execution.hpp>
#include <exec/start_detached.hpp>
#include <exec/task.hpp>

#include <atomic>
#include <chrono>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <utility>

namespace demo::api {

namespace {

std::mutex g_mu;
std::unique_ptr<WorkerRuntime> g_worker_a;
std::unique_ptr<WorkerRuntime> g_worker_b;
std::atomic<std::uint32_t> g_ping_counter{0};

// Launch a coroutine/sender on the bridge io thread.
template <class S>
void spawn_on_io(S&& sndr) {
  exec::start_detached(
      stdexec::starts_on(*dcb::Runtime::instance().io_scheduler(),
                         std::forward<S>(sndr)));
}

// ─── Worker A / B coroutine bodies (static, run on the worker loops) ───

exec::task<void> process_message_on_a(co::oneshot::Sender<std::string> tx,
                                      std::string msg) {
  // Runs on Worker A's event loop thread.
  std::string result = "[A:" + msg + "]";
  tx.send(std::move(result));  // non-blocking send back to Main
  co_return;
}

exec::task<void> ping_worker_on_b(co::oneshot::Sender<std::string> tx,
                                  std::string payload, std::uint32_t id) {
  // Runs on Worker B's event loop thread.
  std::string result = "[B#" + std::to_string(id) + ":" + payload + "]";
  tx.send(std::move(result));
  co_return;
}

exec::task<void> pipeline_stage1_on_a(co::oneshot::Sender<std::string> tx_ab,
                                      std::string msg) {
  std::string stage1 = "A{" + msg + "}";
  tx_ab.send(std::move(stage1));
  co_return;
}

exec::task<void> pipeline_stage2_on_b(co::oneshot::Receiver<std::string> rx_ab,
                                      co::oneshot::Sender<std::string> tx_final) {
  auto from_a = co_await std::move(rx_ab);
  if (!from_a) {
    tx_final.send(std::string("pipeline: A dropped"));
    co_return;
  }
  std::string stage2 = "B[" + *from_a + "]";
  tx_final.send(std::move(stage2));
  co_return;
}

exec::task<void> fan_out_on_a(co::oneshot::Sender<std::string> tx,
                              std::string msg) {
  tx.send("A:" + msg);
  co_return;
}

exec::task<void> fan_out_on_b(co::oneshot::Sender<std::string> tx,
                              std::string msg) {
  tx.send("B:" + msg);
  co_return;
}

exec::task<void> worker_stream_produce(co::mpsc::Sender<std::string> tx,
                                       std::int32_t count,
                                       std::int32_t interval_ms) {
  for (std::int32_t i = 0; i < count; ++i) {
    if (interval_ms > 0) {
      std::this_thread::sleep_for(std::chrono::milliseconds(interval_ms));
    }
    if (!tx.send("item_" + std::to_string(i))) {
      break;  // receiver gone
    }
  }
  // tx dropped here → channel closes → recv returns nullopt
  co_return;
}

exec::task<void> worker_stream_forward(dcb::StreamSink<std::string> sink,
                                       co::mpsc::Receiver<std::string> rx) {
  while (true) {
    auto item = co_await rx.recv();
    if (!item) break;  // channel closed
    sink.add(*item);
  }
  sink.end();
  co_return;
}

exec::task<void> call_dart_from_worker(
    co::oneshot::Sender<std::string> tx,
    dcb::DartFn<std::string(std::string)> cb, std::string input) {
  try {
    auto result = co_await cb(input);
    tx.send(std::move(result));
  } catch (const std::exception& e) {
    tx.send(std::string("ERROR: ") + e.what());
  }
  co_return;
}

}  // namespace

exec::task<std::string> start_workers() {
  std::lock_guard lock(g_mu);
  if (!g_worker_a) {
    g_worker_a = std::make_unique<WorkerRuntime>("processor");
    g_worker_a->start();
  }
  if (!g_worker_b) {
    g_worker_b = std::make_unique<WorkerRuntime>("responder");
    g_worker_b->start();
  }
  co_return std::string("workers started");
}

exec::task<std::string> stop_workers() {
  std::lock_guard lock(g_mu);
  if (g_worker_a) g_worker_a->stop();
  if (g_worker_b) g_worker_b->stop();
  g_worker_a.reset();
  g_worker_b.reset();
  co_return std::string("workers stopped");
}

exec::task<std::string> process_message(std::string message) {
  auto [tx, rx] = co::oneshot::channel<std::string>();

  {
    std::lock_guard lock(g_mu);
    if (!g_worker_a || !g_worker_a->running()) {
      throw std::runtime_error("worker A not running");
    }
    g_worker_a->spawn(process_message_on_a(std::move(tx), std::move(message)));
  }

  // Await Worker A's reply (suspends coroutine, doesn't block thread).
  auto reply = co_await std::move(rx);
  if (!reply) {
    throw std::runtime_error("worker A dropped");
  }
  co_return *reply;
}

exec::task<std::string> ping_worker(std::string payload) {
  auto [tx, rx] = co::oneshot::channel<std::string>();

  {
    std::lock_guard lock(g_mu);
    if (!g_worker_b || !g_worker_b->running()) {
      throw std::runtime_error("worker B not running");
    }
    auto id = g_ping_counter.fetch_add(1, std::memory_order_relaxed);
    g_worker_b->spawn(ping_worker_on_b(std::move(tx), std::move(payload), id));
  }

  auto reply = co_await std::move(rx);
  if (!reply) {
    throw std::runtime_error("worker B dropped");
  }
  co_return *reply;
}

exec::task<std::string> pipeline(std::string message) {
  // Final reply channel (Worker B → Main).
  auto [tx_final, rx_final] = co::oneshot::channel<std::string>();
  // Intermediate channel (Worker A → Worker B).
  auto [tx_ab, rx_ab] = co::oneshot::channel<std::string>();

  {
    std::lock_guard lock(g_mu);
    if (!g_worker_a || !g_worker_a->running() ||
        !g_worker_b || !g_worker_b->running()) {
      throw std::runtime_error("workers not running");
    }

    // Stage 1: Worker A processes and sends to Worker B.
    g_worker_a->spawn(pipeline_stage1_on_a(std::move(tx_ab), std::move(message)));

    // Stage 2: Worker B awaits A's output, processes, sends final.
    g_worker_b->spawn(pipeline_stage2_on_b(std::move(rx_ab), std::move(tx_final)));
  }

  // Await final result.
  auto reply = co_await std::move(rx_final);
  co_return reply.value_or("pipeline: lost");
}

exec::task<std::pair<std::string, std::string>> fan_out(
    std::string message) {
  auto [tx_a, rx_a] = co::oneshot::channel<std::string>();
  auto [tx_b, rx_b] = co::oneshot::channel<std::string>();

  {
    std::lock_guard lock(g_mu);
    if (!g_worker_a || !g_worker_a->running() ||
        !g_worker_b || !g_worker_b->running()) {
      throw std::runtime_error("workers not running");
    }

    g_worker_a->spawn(fan_out_on_a(std::move(tx_a), message));
    g_worker_b->spawn(fan_out_on_b(std::move(tx_b), message));
  }

  // Await both replies (workers run in parallel).
  auto a = co_await std::move(rx_a);
  auto b = co_await std::move(rx_b);
  co_return std::make_pair(a.value_or("A:lost"), b.value_or("B:lost"));
}

void worker_stream(dcb::StreamSink<std::string> sink, std::int32_t count,
                   std::int32_t interval_ms) {
  // mpsc channel: Worker A (producer) → Main coroutine (consumer → Dart stream).
  auto [tx, rx] = co::mpsc::unbounded<std::string>();

  {
    std::lock_guard lock(g_mu);
    if (!g_worker_a || !g_worker_a->running()) {
      sink.error("worker A not running");
      return;
    }

    // Worker A: emit items with delay.
    g_worker_a->spawn(worker_stream_produce(std::move(tx), count, interval_ms));
  }

  // Spawn a coroutine on the Main runtime to consume mpsc and forward to sink.
  spawn_on_io(worker_stream_forward(std::move(sink), std::move(rx)));
}

exec::task<std::string> call_dart_from_worker_a(
    dcb::DartFn<std::string(std::string)> callback, std::string input) {
  auto [tx, rx] = co::oneshot::channel<std::string>();

  {
    std::lock_guard lock(g_mu);
    if (!g_worker_a || !g_worker_a->running()) {
      throw std::runtime_error("worker A not running");
    }
    // Spawn on Worker A: the coroutine co_awaits the DartFn.
    g_worker_a->spawn(call_dart_from_worker(std::move(tx), std::move(callback),
                                            std::move(input)));
  }

  auto reply = co_await std::move(rx);
  if (!reply) {
    throw std::runtime_error("worker A dropped");
  }
  co_return *reply;
}

exec::task<std::string> call_dart_from_worker_b(
    dcb::DartFn<std::string(std::string)> callback, std::string input) {
  auto [tx, rx] = co::oneshot::channel<std::string>();

  {
    std::lock_guard lock(g_mu);
    if (!g_worker_b || !g_worker_b->running()) {
      throw std::runtime_error("worker B not running");
    }
    g_worker_b->spawn(call_dart_from_worker(std::move(tx), std::move(callback),
                                            std::move(input)));
  }

  auto reply = co_await std::move(rx);
  if (!reply) {
    throw std::runtime_error("worker B dropped");
  }
  co_return *reply;
}

}  // namespace demo::api
