// GENERATED by dart_cpp_bridge codegen — do not edit.
// ignore_for_file: unused_element, unused_import

import 'dart:async';
import 'dart:typed_data';

import 'package:dart_cpp_bridge/dart_cpp_bridge.dart';



/// Wire-level API singleton. Access via [BridgeApiImpl.instance].
final class BridgeApiImpl {
  BridgeApiImpl._(this.bridge);

  final DartCppBridge bridge;

  // ── Singleton ──
  static BridgeApiImpl? _instance;
  static BridgeApiImpl get instance {
    final i = _instance;
    if (i == null) throw StateError('DcbLib.init() must be called first');
    return i;
  }
  static void initSingleton(DartCppBridge bridge) => _instance = BridgeApiImpl._(bridge);
  static void disposeSingleton() => _instance = null;

  static const int callDartFromWorkerAId = 38396996;
  static const int stopWorkersId = 489867174;
  static const int callDartFromWorkerBId = 568428227;
  static const int startWorkersId = 802585972;
  static const int pingWorkerId = 812353966;
  static const int processMessageId = 1706202089;
  static const int pipelineId = 1761426519;
  static const int fanOutId = 2046595992;
  static const int workerStreamId = 2109241176;

  Future<String> callDartFromWorkerA(Future<String> Function(String) callback, String input) async {
    final _callbackWrapper = (Uint8List _argBytes) async {
      final _r = ByteReader(_argBytes);
      final _a0 = _r.str();
      final _res = await callback(_a0);
      final _w = ByteWriter();
      _w.str(_res);
      return _w.takeBytes();
    };
    final _callbackId = bridge.registerDartFn(_callbackWrapper);
    try {
      final _payload = ByteWriter();
      _payload.u64(_callbackId);
      _payload.str(input);
      final _payloadBytes = _payload.takeBytes();
      final _bytes = await bridge.invokeAsyncMethod(callDartFromWorkerAId, _payloadBytes);
      return ByteReader(_bytes).str();
    } finally {
      bridge.unregisterDartFn(_callbackId);
    }
  }

  Future<String> stopWorkers() async {
    final _payload = ByteWriter();
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(stopWorkersId, _payloadBytes);
    return ByteReader(_bytes).str();
  }

  Future<String> callDartFromWorkerB(Future<String> Function(String) callback, String input) async {
    final _callbackWrapper = (Uint8List _argBytes) async {
      final _r = ByteReader(_argBytes);
      final _a0 = _r.str();
      final _res = await callback(_a0);
      final _w = ByteWriter();
      _w.str(_res);
      return _w.takeBytes();
    };
    final _callbackId = bridge.registerDartFn(_callbackWrapper);
    try {
      final _payload = ByteWriter();
      _payload.u64(_callbackId);
      _payload.str(input);
      final _payloadBytes = _payload.takeBytes();
      final _bytes = await bridge.invokeAsyncMethod(callDartFromWorkerBId, _payloadBytes);
      return ByteReader(_bytes).str();
    } finally {
      bridge.unregisterDartFn(_callbackId);
    }
  }

  Future<String> startWorkers() async {
    final _payload = ByteWriter();
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(startWorkersId, _payloadBytes);
    return ByteReader(_bytes).str();
  }

  Future<String> pingWorker(String payload) async {
    final _payload = ByteWriter();
    _payload.str(payload);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(pingWorkerId, _payloadBytes);
    return ByteReader(_bytes).str();
  }

  Future<String> processMessage(String message) async {
    final _payload = ByteWriter();
    _payload.str(message);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(processMessageId, _payloadBytes);
    return ByteReader(_bytes).str();
  }

  Future<String> pipeline(String message) async {
    final _payload = ByteWriter();
    _payload.str(message);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(pipelineId, _payloadBytes);
    return ByteReader(_bytes).str();
  }

  Future<(String, String)> fanOut(String message) async {
    final _payload = ByteWriter();
    _payload.str(message);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(fanOutId, _payloadBytes);
    return (() { final _r = ByteReader(_bytes); return (_r.str(), _r.str()); })();
  }

  Stream<String> workerStream(int count, int intervalMs) {
    final _payload = ByteWriter();
    _payload.i32(count);
    _payload.i32(intervalMs);
    return bridge.openStream<String>(workerStreamId, _payload.takeBytes(), (final _r) => _r.str());
  }
}
