import 'dart:ffi';

import 'package:ffi/ffi.dart';

// ---------------------------------------------------------------------------
// C ABI typedefs for the dcb_* runtime exports.
// ---------------------------------------------------------------------------

typedef InitDartApiC = IntPtr Function(Pointer<Void>);
typedef InitDartApiD = int Function(Pointer<Void>);

typedef SessionOpenC = Uint64 Function(Int64);
typedef SessionOpenD = int Function(int);

typedef SessionCloseC = Void Function(Uint64);
typedef SessionCloseD = void Function(int);

typedef ShutdownC = Void Function();
typedef ShutdownD = void Function();

typedef InvokeSyncC = Pointer<Uint8> Function(
  Uint64,
  Pointer<Uint8>,
  IntPtr,
  Pointer<IntPtr>,
  Pointer<Pointer<Utf8>>,
);
typedef InvokeSyncD = Pointer<Uint8> Function(
  int,
  Pointer<Uint8>,
  int,
  Pointer<IntPtr>,
  Pointer<Pointer<Utf8>>,
);

typedef InvokeAsyncC = Void Function(Uint64, Pointer<Uint8>, IntPtr);
typedef InvokeAsyncD = void Function(int, Pointer<Uint8>, int);

typedef StreamCloseC = Void Function(Uint64, Uint64);
typedef StreamCloseD = void Function(int, int);

typedef DartFnReplyC = Void Function(
  Uint64,
  Uint64,
  Uint8,
  Pointer<Uint8>,
  IntPtr,
  Pointer<Utf8>,
);
typedef DartFnReplyD = void Function(
  int,
  int,
  int,
  Pointer<Uint8>,
  int,
  Pointer<Utf8>,
);

typedef FreeC = Void Function(Pointer<Void>);
typedef FreeD = void Function(Pointer<Void>);

typedef SetVerboseErrorsC = Void Function(Uint8);
typedef SetVerboseErrorsD = void Function(int);
typedef SetPoolThreadsC = Void Function(Uint32);
typedef SetPoolThreadsD = void Function(int);

typedef FinalizerFn = NativeFunction<Void Function(Pointer<Void>)>;

// ---------------------------------------------------------------------------
// NativeBindings: resolved function pointers to the dcb_* C ABI.
// ---------------------------------------------------------------------------

/// Resolved native function pointers for the dart_cpp_bridge C ABI.
///
/// Created by downstream packages from `@Native` externals (generated by
/// codegen into the user's package so that the asset ID resolves correctly).
///
/// ```dart
/// // In generated dcb_bindings.dart (user package):
/// @Native<InitDartApiC>(symbol: 'dcb_init_dart_api')
/// external int _dcbInitDartApi(Pointer<Void> data);
/// // ...
/// NativeBindings createDcbBindings() => NativeBindings(...);
/// ```
class NativeBindings {
  const NativeBindings({
    required this.initDartApi,
    required this.sessionOpen,
    required this.sessionClose,
    required this.sessionFinalizer,
    required this.shutdown,
    required this.invokeSync,
    required this.invokeAsync,
    required this.streamClose,
    required this.dartFnReply,
    required this.free,
    required this.setVerboseErrors,
    required this.setPoolThreads,
    required this.dropObject,
  });

  final InitDartApiD initDartApi;
  final SessionOpenD sessionOpen;
  final SessionCloseD sessionClose;
  final Pointer<FinalizerFn> sessionFinalizer;
  final ShutdownD shutdown;
  final InvokeSyncD invokeSync;
  final InvokeAsyncD invokeAsync;
  final StreamCloseD streamClose;
  final DartFnReplyD dartFnReply;
  final FreeD free;
  final SetVerboseErrorsD setVerboseErrors;
  final SetPoolThreadsD setPoolThreads;
  final Pointer<FinalizerFn> dropObject;
}
