// GENERATED by dart_cpp_bridge codegen — do not edit.
// Source: bridge_api.h

import 'dart:async';

import '../gcm_generated.dart';

export '../gcm_generated.dart' show OrderStatus;

// ═════════════════════════════════════════════
// Data classes
// ═════════════════════════════════════════════

/// Generated data class for `demo::api::Point`.
final class Point {
  const Point({
    required this.x,
    required this.y,
  });

  final double x;
  final double y;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is Point &&
        x == other.x &&
        y == other.y);

  @override
  int get hashCode => Object.hash(x, y);

  @override
  String toString() => 'Point(x: $x, y: $y)';
}

/// Generated data class for `demo::api::Rect`.
final class Rect {
  const Rect({
    required this.topLeft,
    required this.bottomRight,
  });

  final Point topLeft;
  final Point bottomRight;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is Rect &&
        topLeft == other.topLeft &&
        bottomRight == other.bottomRight);

  @override
  int get hashCode => Object.hash(topLeft, bottomRight);

  @override
  String toString() => 'Rect[$topLeft -> $bottomRight]';
}

// ═════════════════════════════════════════════
// Functions
// ═════════════════════════════════════════════

Future<int> sumScores({required Map<String, int> scores}) => BridgeApiImpl.instance.sumScores(scores);

Future<double> distance({required Point a, required Point b}) => BridgeApiImpl.instance.distance(a, b);

Future<int> failNormal({required String msg}) => BridgeApiImpl.instance.failNormal(msg);

Future<(int, String)> pairEcho({required (int, String) value}) => BridgeApiImpl.instance.pairEcho(value);

Future<(int, String, bool)> tupleEcho({required (int, String, bool) value}) => BridgeApiImpl.instance.tupleEcho(value);

Future<int> failAsync({required String msg}) => BridgeApiImpl.instance.failAsync(msg);

Stream<int> failStream({required String msg}) => BridgeApiImpl.instance.failStream(msg);

Future<String> downloadWithProgress({required String url, StreamController<int>? progress}) => BridgeApiImpl.instance.downloadWithProgress(url, progress);

Future<int?> maybeDouble({int? value}) => BridgeApiImpl.instance.maybeDouble(value);

Future<int> add({required int a, required int b}) => BridgeApiImpl.instance.add(a, b);

int bridgeVersion() => BridgeApiImpl.instance.bridgeVersion();

Future<int> sumArray({required List<int> values}) => BridgeApiImpl.instance.sumArray(values);

Future<int> incrementI64({required int value}) => BridgeApiImpl.instance.incrementI64(value);

Future<OrderStatus?> optionalStatus({OrderStatus? value}) => BridgeApiImpl.instance.optionalStatus(value);

Future<List<int>> echoList({required List<int> values}) => BridgeApiImpl.instance.echoList(values);

Future<Point> scale({required Point p, required double factor}) => BridgeApiImpl.instance.scale(p, factor);

Future<bool> negateBool({required bool value}) => BridgeApiImpl.instance.negateBool(value);

int failSync({required String msg}) => BridgeApiImpl.instance.failSync(msg);

Future<String> sleepGreeting({required String name}) => BridgeApiImpl.instance.sleepGreeting(name);

Future<BigInt> echoU128({required BigInt value}) => BridgeApiImpl.instance.echoU128(value);

Future<int> failNonStd() => BridgeApiImpl.instance.failNonStd();

Future<int> incrementU32({required int value}) => BridgeApiImpl.instance.incrementU32(value);

Stream<int> tickStream({int count = 5, int intervalMs = 10}) => BridgeApiImpl.instance.tickStream(count, intervalMs);

Future<String> greetDartFn({required FutureOr<String> Function(String) callback, required String name}) => BridgeApiImpl.instance.greetDartFn(callback, name);

List<List<List<int>>> nestedCube({required int n}) => BridgeApiImpl.instance.nestedCube(n);

Future<int> sumSet({required Set<int> values}) => BridgeApiImpl.instance.sumSet(values);

Future<Rect> boundingBox({required List<Point> points}) => BridgeApiImpl.instance.boundingBox(points);

Future<BigInt> echoI128({required BigInt value}) => BridgeApiImpl.instance.echoI128(value);

Future<String?> optionalString({String? value}) => BridgeApiImpl.instance.optionalString(value);

Future<OrderStatus> nextStatus({required OrderStatus current}) => BridgeApiImpl.instance.nextStatus(current);
