// GENERATED by dart_cpp_bridge codegen — do not edit.
// Source: counter.h

import 'dart:async';

import 'package:dart_cpp_bridge/dart_cpp_bridge.dart';

import '../gcm_generated.dart';
import 'init.dart';

// ═════════════════════════════════════════════
// Counter
// ═════════════════════════════════════════════

/// Opaque wrapper for `demo::api::Counter`.
final class Counter extends CppOpaqueInterface {
  Counter._({required super.bridge, required super.handle});

  // ── Constructors ──

  factory Counter.int32T({required int initialValue}) => Counter._(
        bridge: DcbLib.bridge,
        handle: BridgeApiImpl.instance.counterNewWithInitialValue(initialValue),
      );

  factory Counter() => Counter._(
        bridge: DcbLib.bridge,
        handle: BridgeApiImpl.instance.counterNew(),
      );

  // ── Instance Methods ──

  Future<int> value() async {
    ensureAlive();
    return await BridgeApiImpl.instance.counterValue(handle);
  }

  int valueSync() {
    ensureAlive();
    return BridgeApiImpl.instance.counterValueSync(handle);
  }

  Future<void> increment({int delta = 1}) async {
    ensureAlive();
    await BridgeApiImpl.instance.counterIncrement(handle, delta);
  }

  Future<int> sleepAndGet({required int sleepMs}) async {
    ensureAlive();
    return await BridgeApiImpl.instance.counterSleepAndGet(handle, sleepMs);
  }

  Future<int> addList({required List<int> values}) async {
    ensureAlive();
    return await BridgeApiImpl.instance.counterAddList(handle, values);
  }

  Future<void> setValue({int? value}) async {
    ensureAlive();
    await BridgeApiImpl.instance.counterSetValue(handle, value);
  }

  Future<Counter> duplicate() async {
    ensureAlive();
    final newHandle = await BridgeApiImpl.instance.counterDuplicate(handle);
    return Counter._(bridge: DcbLib.bridge, handle: newHandle);
  }

  Future<String> greetDartFn({required FutureOr<String> Function(String) callback, required String name}) async {
    ensureAlive();
    return await BridgeApiImpl.instance.counterGreetDartFn(handle, callback, name);
  }

  Stream<int> tickStream({int count = 5, int intervalMs = 10}) {
    ensureAlive();
    return BridgeApiImpl.instance.counterTickStream(handle, count, intervalMs);
  }

  // ── Static Methods ──

  static int sum({required int a, required int b}) {
    return BridgeApiImpl.instance.counterSum(a, b);
  }

  static int aliveCount() {
    return BridgeApiImpl.instance.counterAliveCount();
  }

}
