// GENERATED by dart_cpp_bridge codegen — do not edit.
// Source: foreign_api.h

import 'dart:async';

import '../dcb_generated.dart';

// ═════════════════════════════════════════════
// Functions
// ═════════════════════════════════════════════

Future<String> callDartFromUv({
  required Future<String> Function(String) callback,
  required String input,
}) => BridgeApiImpl.instance.callDartFromUv(callback, input);

Future<String> stopUvWorker() => BridgeApiImpl.instance.stopUvWorker();

Future<String> startUvWorker() => BridgeApiImpl.instance.startUvWorker();

Future<String> testCbridgeInvoke({
  required Future<String> Function(String) callback,
  required String input,
}) => BridgeApiImpl.instance.testCbridgeInvoke(callback, input);

Future<String> testCbridgeAsync() => BridgeApiImpl.instance.testCbridgeAsync();

Future<String> testChannelServiceConcurrent() =>
    BridgeApiImpl.instance.testChannelServiceConcurrent();

Future<String> testCbridgeInvokePureC({
  required Future<String> Function(String) callback,
  required String input,
}) => BridgeApiImpl.instance.testCbridgeInvokePureC(callback, input);

Future<String> testCbridgeAsyncFail() =>
    BridgeApiImpl.instance.testCbridgeAsyncFail();

Future<int> uvCompute({required int n}) => BridgeApiImpl.instance.uvCompute(n);

Future<String> askUv({required String message}) =>
    BridgeApiImpl.instance.askUv(message);

Future<String> testCbridgeAsyncCancel() =>
    BridgeApiImpl.instance.testCbridgeAsyncCancel();

Stream<String> uvStream({int count = 5, int intervalMs = 50}) =>
    BridgeApiImpl.instance.uvStream(count, intervalMs);

Future<String> testChannelService() =>
    BridgeApiImpl.instance.testChannelService();
