// GENERATED by dart_cpp_bridge codegen — do not edit.
// Public singleton facade (also used by top-level api_fn.dart).

import 'dart:async';

import 'package:dart_cpp_bridge/dart_cpp_bridge.dart' hide Counter;

export 'api.g.dart';
import 'api.g.dart';

/// App-facing API singleton.
///
/// Prefer top-level helpers in `api_fn.dart` for call sites:
/// `await initBridge(...); final v = bridgeVersion();`
final class BridgeApi {
  BridgeApi._();

  static final BridgeApi instance = BridgeApi._();

  BridgeApiImpl? _implOrNull;
  DartCppBridge? _bridgeOrNull;

  BridgeApiImpl get _impl {
    final impl = _implOrNull;
    if (impl == null) {
      throw StateError('BridgeApi.init() must be called first');
    }
    return impl;
  }

  /// Underlying session bridge (after [init]).
  DartCppBridge get bridge {
    final b = _bridgeOrNull;
    if (b == null) {
      throw StateError('BridgeApi.init() must be called first');
    }
    return b;
  }

  bool get isInitialized => _implOrNull != null;

  /// Open the per-isolate session and bind generated impl.
  Future<void> init({String? libraryPath}) async {
    if (_implOrNull != null) {
      return;
    }
    final b = await DartCppBridge.init(libraryPath: libraryPath);
    _bridgeOrNull = b;
    _implOrNull = BridgeApiImpl(b);
  }

  /// Prompt dispose of this isolate session (optional; finalizer also closes).
  void dispose() {
    _bridgeOrNull?.dispose();
    _bridgeOrNull = null;
    _implOrNull = null;
  }

  /// Process-wide runtime shutdown (main isolate / app exit only).
  void shutdown() {
    _bridgeOrNull?.shutdown();
    _bridgeOrNull = null;
    _implOrNull = null;
  }

  Future<int> sumScores(Map<String, int> scores) => _impl.sumScores(scores);
  Future<double> distance(Point a, Point b) => _impl.distance(a, b);
  Future<(int, String)> pairEcho((int, String) value) => _impl.pairEcho(value);
  Future<(int, String, bool)> tupleEcho((int, String, bool) value) => _impl.tupleEcho(value);
  Future<int?> maybeDouble(int? value) => _impl.maybeDouble(value);
  Future<int> add(int a, int b) => _impl.add(a, b);
  int bridgeVersion() => _impl.bridgeVersion();
  Future<int> sumArray(List<int> values) => _impl.sumArray(values);
  Future<int> incrementI64(int value) => _impl.incrementI64(value);
  Future<OrderStatus?> optionalStatus(OrderStatus? value) => _impl.optionalStatus(value);
  Future<List<int>> echoList(List<int> values) => _impl.echoList(values);
  Future<Point> scale(Point p, double factor) => _impl.scale(p, factor);
  Future<bool> negateBool(bool value) => _impl.negateBool(value);
  Future<String> sleepGreeting(String name) => _impl.sleepGreeting(name);
  Future<BigInt> echoU128(BigInt value) => _impl.echoU128(value);
  Future<int> incrementU32(int value) => _impl.incrementU32(value);
  Stream<int> tickStream(int count, int intervalMs) => _impl.tickStream(count, intervalMs);
  Future<String> greetDartFn(FutureOr<String> Function(String) callback, String name) => _impl.greetDartFn(callback, name);
  Future<int> sumSet(Set<int> values) => _impl.sumSet(values);
  Future<Rect> boundingBox(List<Point> points) => _impl.boundingBox(points);
  Future<BigInt> echoI128(BigInt value) => _impl.echoI128(value);
  Future<String?> optionalString(String? value) => _impl.optionalString(value);
  Future<OrderStatus> nextStatus(OrderStatus current) => _impl.nextStatus(current);
  int counterNewWithInitialValue(int initialValue) => _impl.counterNewWithInitialValue(initialValue);
  int counterNew() => _impl.counterNew();
  Future<int> counterValue(int handle) async => _impl.counterValue(handle);
  int counterValueSync(int handle) => _impl.counterValueSync(handle);
  Future<void> counterIncrement(int handle, int delta) async => _impl.counterIncrement(handle, delta);
  Future<int> counterSleepAndGet(int handle, int sleepMs) async => _impl.counterSleepAndGet(handle, sleepMs);
  Future<int> counterAddList(int handle, List<int> values) async => _impl.counterAddList(handle, values);
  Future<void> counterSetValue(int handle, int? value) async => _impl.counterSetValue(handle, value);
  Future<int> counterDuplicate(int handle) async => _impl.counterDuplicate(handle);
  int counterSum(int a, int b) => _impl.counterSum(a, b);
  Future<String> counterGreetDartFn(int handle, FutureOr<String> Function(String) callback, String name) async => _impl.counterGreetDartFn(handle, callback, name);
  Stream<int> counterTickStream(int handle, int count, int intervalMs) => _impl.counterTickStream(handle, count, intervalMs);
}


final class Counter extends CppOpaqueInterface {
  Counter._({required super.bridge, required super.handle});

  factory Counter.withInitialValue({required int initialValue}) => Counter._(bridge: BridgeApi.instance.bridge, handle: BridgeApi.instance.counterNewWithInitialValue(initialValue));
  factory Counter() => Counter._(bridge: BridgeApi.instance.bridge, handle: BridgeApi.instance.counterNew());

  Future<int> value() async {
    ensureAlive();
    return await BridgeApi.instance.counterValue(handle);
  }
  int valueSync() {
    ensureAlive();
    return BridgeApi.instance.counterValueSync(handle);
  }
  Future<void> increment([int delta = 1]) async {
    ensureAlive();
    await BridgeApi.instance.counterIncrement(handle, delta);
  }
  Future<int> sleepAndGet(int sleepMs) async {
    ensureAlive();
    return await BridgeApi.instance.counterSleepAndGet(handle, sleepMs);
  }
  Future<int> addList(List<int> values) async {
    ensureAlive();
    return await BridgeApi.instance.counterAddList(handle, values);
  }
  Future<void> setValue(int? value) async {
    ensureAlive();
    await BridgeApi.instance.counterSetValue(handle, value);
  }
  Future<Counter> duplicate() async {
    ensureAlive();
    final newHandle = await BridgeApi.instance.counterDuplicate(handle);
    return Counter._(bridge: BridgeApi.instance.bridge, handle: newHandle);
  }
  static int sum(int a, int b) {
    return BridgeApi.instance.counterSum(a, b);
  }
  Future<String> greetDartFn(FutureOr<String> Function(String) callback, String name) async {
    ensureAlive();
    return await BridgeApi.instance.counterGreetDartFn(handle, callback, name);
  }
  Stream<int> tickStream([int count = 5, int intervalMs = 10]) {
    ensureAlive();
    return BridgeApi.instance.counterTickStream(handle, count, intervalMs);
  }
}

