// GENERATED by dart_cpp_bridge codegen — do not edit.
// Low-level impl (method ids + wire). Prefer importing api.dart singleton.

import 'dart:typed_data';

import 'package:dart_cpp_bridge/dart_cpp_bridge.dart';

/// Generated enum for `demo::api::OrderStatus`.
enum OrderStatus {
  created,
  paid,
  shipped,
}

/// Wire-level API. Prefer [BridgeApi.instance] from `api.dart`.
final class BridgeApiImpl {
  BridgeApiImpl(this.bridge);

  final DartCppBridge bridge;

  static const int maybeDoubleId = 489154044;
  static const int addId = 513277594;
  static const int bridgeVersionId = 513280939;
  static const int sleepGreetingId = 1347623235;
  static const int nextStatusId = 2129366549;

  Future<int?> maybeDouble(int? value) async {
    final _payload = ByteWriter();
    if (value == null) { _payload.u8(0); } else { _payload.u8(1);
      _payload.i32(value);
    }
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(maybeDoubleId, _payloadBytes);
    return (() { final _r = ByteReader(_bytes); final _has = _r.u8() != 0; return _has ? _r.i32() : null; })();
  }

  Future<int> add(int a, int b) async {
    final _payload = ByteWriter();
    _payload.i32(a);
    _payload.i32(b);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(addId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  int bridgeVersion() {
    final _payloadBytes = Uint8List(0);
    final _bytes = bridge.invokeSyncMethod(bridgeVersionId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  Future<String> sleepGreeting(String name) async {
    final _payload = ByteWriter();
    _payload.str(name);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(sleepGreetingId, _payloadBytes);
    return ByteReader(_bytes).str();
  }

  Future<OrderStatus> nextStatus(OrderStatus current) async {
    final _payload = ByteWriter();
    _payload.i32(current.index);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(nextStatusId, _payloadBytes);
    return OrderStatus.values[ByteReader(_bytes).i32()];
  }
}
