// GENERATED by dart_cpp_bridge codegen — do not edit.
// Public singleton facade (also used by top-level api_fn.dart).

import 'package:dart_cpp_bridge/dart_cpp_bridge.dart';

export 'api.g.dart';
import 'api.g.dart';

/// App-facing API singleton.
///
/// Prefer top-level helpers in `api_fn.dart` for call sites:
/// `await initBridge(...); final v = bridgeVersion();`
final class BridgeApi {
  BridgeApi._();

  static final BridgeApi instance = BridgeApi._();

  BridgeApiImpl? _implOrNull;
  DartCppBridge? _bridgeOrNull;

  BridgeApiImpl get _impl {
    final impl = _implOrNull;
    if (impl == null) {
      throw StateError('BridgeApi.init() must be called first');
    }
    return impl;
  }

  /// Underlying session bridge (after [init]).
  DartCppBridge get bridge {
    final b = _bridgeOrNull;
    if (b == null) {
      throw StateError('BridgeApi.init() must be called first');
    }
    return b;
  }

  bool get isInitialized => _implOrNull != null;

  /// Open the per-isolate session and bind generated impl.
  Future<void> init({String? libraryPath}) async {
    if (_implOrNull != null) {
      return;
    }
    final b = await DartCppBridge.init(libraryPath: libraryPath);
    _bridgeOrNull = b;
    _implOrNull = BridgeApiImpl(b);
  }

  /// Prompt dispose of this isolate session (optional; finalizer also closes).
  void dispose() {
    _bridgeOrNull?.dispose();
    _bridgeOrNull = null;
    _implOrNull = null;
  }

  /// Process-wide runtime shutdown (main isolate / app exit only).
  void shutdown() {
    _bridgeOrNull?.shutdown();
    _bridgeOrNull = null;
    _implOrNull = null;
  }

  Future<int> sumScores(Map<String, int> scores) => _impl.sumScores(scores);
  Future<int?> maybeDouble(int? value) => _impl.maybeDouble(value);
  Future<int> add(int a, int b) => _impl.add(a, b);
  int bridgeVersion() => _impl.bridgeVersion();
  Future<int> sumArray(List<int> values) => _impl.sumArray(values);
  Future<int> incrementI64(int value) => _impl.incrementI64(value);
  Future<OrderStatus?> optionalStatus(OrderStatus? value) => _impl.optionalStatus(value);
  Future<List<int>> echoList(List<int> values) => _impl.echoList(values);
  Future<bool> negateBool(bool value) => _impl.negateBool(value);
  Future<String> sleepGreeting(String name) => _impl.sleepGreeting(name);
  Future<BigInt> echoU128(BigInt value) => _impl.echoU128(value);
  Future<int> incrementU32(int value) => _impl.incrementU32(value);
  Future<int> sumSet(Set<int> values) => _impl.sumSet(values);
  Future<BigInt> echoI128(BigInt value) => _impl.echoI128(value);
  Future<String?> optionalString(String? value) => _impl.optionalString(value);
  Future<OrderStatus> nextStatus(OrderStatus current) => _impl.nextStatus(current);
}
