// GENERATED by dart_cpp_bridge codegen — do not edit.
// Top-level API — call like plain functions after initBridge().

import 'dart:async';

import 'api.dart';

/// Initialize the bridge (per isolate). Required before other top-level APIs.
Future<void> initBridge({String? libraryPath}) =>
    BridgeApi.instance.init(libraryPath: libraryPath);

/// Optional prompt session dispose.
void disposeBridge() => BridgeApi.instance.dispose();

/// Process-wide runtime shutdown (main isolate / app exit only).
void shutdownBridge() => BridgeApi.instance.shutdown();

Future<int> sumScores(Map<String, int> scores) =>
    BridgeApi.instance.sumScores(scores);

Future<(int, String)> pairEcho((int, String) value) =>
    BridgeApi.instance.pairEcho(value);

Future<(int, String, bool)> tupleEcho((int, String, bool) value) =>
    BridgeApi.instance.tupleEcho(value);

Future<int?> maybeDouble(int? value) =>
    BridgeApi.instance.maybeDouble(value);

Future<int> add(int a, int b) =>
    BridgeApi.instance.add(a, b);

int bridgeVersion() =>
    BridgeApi.instance.bridgeVersion();

Future<int> sumArray(List<int> values) =>
    BridgeApi.instance.sumArray(values);

Future<int> incrementI64(int value) =>
    BridgeApi.instance.incrementI64(value);

Future<OrderStatus?> optionalStatus(OrderStatus? value) =>
    BridgeApi.instance.optionalStatus(value);

Future<List<int>> echoList(List<int> values) =>
    BridgeApi.instance.echoList(values);

Future<bool> negateBool(bool value) =>
    BridgeApi.instance.negateBool(value);

Future<String> sleepGreeting(String name) =>
    BridgeApi.instance.sleepGreeting(name);

Future<BigInt> echoU128(BigInt value) =>
    BridgeApi.instance.echoU128(value);

Future<int> incrementU32(int value) =>
    BridgeApi.instance.incrementU32(value);

Future<String> greetDartFn(FutureOr<String> Function(String) callback, String name) =>
    BridgeApi.instance.greetDartFn(callback, name);

Future<int> sumSet(Set<int> values) =>
    BridgeApi.instance.sumSet(values);

Future<BigInt> echoI128(BigInt value) =>
    BridgeApi.instance.echoI128(value);

Future<String?> optionalString(String? value) =>
    BridgeApi.instance.optionalString(value);

Future<OrderStatus> nextStatus(OrderStatus current) =>
    BridgeApi.instance.nextStatus(current);
