// GENERATED by dart_cpp_bridge codegen — do not edit.
// Top-level API — call like plain functions after initBridge().

import 'api.dart';

/// Initialize the bridge (per isolate). Required before other top-level APIs.
Future<void> initBridge({String? libraryPath}) =>
    BridgeApi.instance.init(libraryPath: libraryPath);

/// Optional prompt session dispose.
void disposeBridge() => BridgeApi.instance.dispose();

/// Process-wide runtime shutdown (main isolate / app exit only).
void shutdownBridge() => BridgeApi.instance.shutdown();

Future<int?> maybeDouble(int? value) =>
    BridgeApi.instance.maybeDouble(value);

Future<int> add(int a, int b) =>
    BridgeApi.instance.add(a, b);

int bridgeVersion() =>
    BridgeApi.instance.bridgeVersion();

Future<int> incrementI64(int value) =>
    BridgeApi.instance.incrementI64(value);

Future<OrderStatus?> optionalStatus(OrderStatus? value) =>
    BridgeApi.instance.optionalStatus(value);

Future<bool> negateBool(bool value) =>
    BridgeApi.instance.negateBool(value);

Future<String> sleepGreeting(String name) =>
    BridgeApi.instance.sleepGreeting(name);

Future<int> incrementU32(int value) =>
    BridgeApi.instance.incrementU32(value);

Future<String?> optionalString(String? value) =>
    BridgeApi.instance.optionalString(value);

Future<OrderStatus> nextStatus(OrderStatus current) =>
    BridgeApi.instance.nextStatus(current);
