// GENERATED by dart_cpp_bridge codegen — do not edit.
// Top-level API — call like plain functions after initBridge().

import 'api.dart';

/// Initialize the bridge (per isolate). Required before other top-level APIs.
Future<void> initBridge({String? libraryPath}) =>
    BridgeApi.instance.init(libraryPath: libraryPath);

/// Optional prompt session dispose.
void disposeBridge() => BridgeApi.instance.dispose();

/// Process-wide runtime shutdown (main isolate / app exit only).
void shutdownBridge() => BridgeApi.instance.shutdown();

Future<int> add(int a, int b) =>
    BridgeApi.instance.add(a, b);

int bridgeVersion() =>
    BridgeApi.instance.bridgeVersion();

Future<String> sleepGreeting(String name) =>
    BridgeApi.instance.sleepGreeting(name);
