// GENERATED by dart_cpp_bridge codegen — do not edit.
// ignore_for_file: unused_element, unused_import

import 'dart:async';
import 'dart:typed_data';

import 'package:dart_cpp_bridge/dart_cpp_bridge.dart';

import 'api/bridge_api.dart';
import 'api/counter.dart';
/// Generated enum for `demo::api::OrderStatus`.
enum OrderStatus {
  created,
  paid,
  shipped,
}

void _writeDataClass_Point(ByteWriter w, Point v) {
  w.f64(v.x);
  w.f64(v.y);
  if (v.label == null) { w.u8(0); } else { w.u8(1);
    w.str(v.label!);
  }
}

Point _readDataClass_Point(ByteReader _r) {
  return Point(
    x: _r.f64(),
    y: _r.f64(),
    label: ((_r.u8() != 0) ? _r.str() : null),
  );
}
void _writeDataClass_Rect(ByteWriter w, Rect v) {
  _writeDataClass_Point(w, v.topLeft);
  _writeDataClass_Point(w, v.bottomRight);
}

Rect _readDataClass_Rect(ByteReader _r) {
  return Rect(
    topLeft: _readDataClass_Point(_r),
    bottomRight: _readDataClass_Point(_r),
  );
}

/// Wire-level API singleton. Access via [BridgeApiImpl.instance].
final class BridgeApiImpl {
  BridgeApiImpl._(this.bridge);

  final DartCppBridge bridge;

  // ── Singleton ──
  static BridgeApiImpl? _instance;
  static BridgeApiImpl get instance {
    final i = _instance;
    if (i == null) throw StateError('DcbLib.init() must be called first');
    return i;
  }
  static void initSingleton(DartCppBridge bridge) => _instance = BridgeApiImpl._(bridge);
  static void disposeSingleton() => _instance = null;

  static const int cloneWithOffsetId = 36494560;
  static const int sumScoresId = 66895156;
  static const int distanceId = 75330037;
  static const int failNormalId = 81397966;
  static const int pairEchoId = 237527086;
  static const int tupleEchoId = 243144110;
  static const int failAsyncId = 414051157;
  static const int failStreamId = 444673125;
  static const int downloadWithProgressId = 463555789;
  static const int maybeDoubleId = 489154044;
  static const int addId = 513277594;
  static const int bridgeVersionId = 513280939;
  static const int sumArrayId = 516316109;
  static const int invokeRegisteredId = 594957055;
  static const int incrementI64Id = 826193512;
  static const int echoTimeId = 861874896;
  static const int optionalStatusId = 923880942;
  static const int echoListId = 923919167;
  static const int invokeRegisteredAsyncId = 999429777;
  static const int concatDartFnId = 1056101777;
  static const int scaleId = 1132741135;
  static const int negateBoolId = 1187695424;
  static const int failSyncId = 1225502033;
  static const int sleepGreetingId = 1347623235;
  static const int echoU128Id = 1349826830;
  static const int echoTimeSyncId = 1426479656;
  static const int failNonStdId = 1517851511;
  static const int addCountersId = 1533879238;
  static const int incrementU32Id = 1597460230;
  static const int tickStreamId = 1673543649;
  static const int registerDartFnId = 1702006080;
  static const int greetDartFnId = 1789823149;
  static const int nestedCubeId = 1812101563;
  static const int sumSetId = 1869545367;
  static const int boundingBoxId = 1914574156;
  static const int syncDartFnBlockingUsId = 2026522337;
  static const int echoI128Id = 2053397325;
  static const int optionalStringId = 2057196713;
  static const int nextStatusId = 2129366549;
  static const int counterNewWithInitialValueId = 546811180;
  static const int counterNewId = 1174608690;
  static const int counterValueId = 1819503097;
  static const int counterValueSyncId = 190346512;
  static const int counterToStringId = 1826397364;
  static const int counterIncrementId = 1534254823;
  static const int counterSleepAndGetId = 809700219;
  static const int counterAddListId = 1623490793;
  static const int counterSetValueId = 1197060560;
  static const int counterDuplicateId = 1724183534;
  static const int counterAddToId = 479175197;
  static const int counterSumId = 1521970656;
  static const int counterGreetDartFnId = 1190014947;
  static const int counterTickStreamId = 550621099;
  static const int counterAliveCountId = 1338263248;

  Counter cloneWithOffset(Counter source, int offset) {
    source.ensureAlive();
    final _payload = ByteWriter();
    _payload.u64(source.handle);
    _payload.i32(offset);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = bridge.invokeSyncMethod(cloneWithOffsetId, _payloadBytes);
    return Counter.fromHandle(bridge: bridge, handle: ByteReader(_bytes).u64());
  }

  Future<int> sumScores(Map<String, int> scores) async {
    final _payload = ByteWriter();
    _payload.u32(scores.length);
    scores.forEach((final _k, final _v) {
      _payload.str(_k);
      _payload.i32(_v);
    });
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(sumScoresId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  Future<double> distance(Point a, Point b) async {
    final _payload = ByteWriter();
    _writeDataClass_Point(_payload, a);
    _writeDataClass_Point(_payload, b);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(distanceId, _payloadBytes);
    return ByteReader(_bytes).f64();
  }

  Future<int> failNormal(String msg) async {
    final _payload = ByteWriter();
    _payload.str(msg);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(failNormalId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  Future<(int, String)> pairEcho((int, String) value) async {
    final _payload = ByteWriter();
    _payload.i32(value.$1);
    _payload.str(value.$2);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(pairEchoId, _payloadBytes);
    return (() { final _r = ByteReader(_bytes); return (_r.i32(), _r.str()); })();
  }

  Future<(int, String, bool)> tupleEcho((int, String, bool) value) async {
    final _payload = ByteWriter();
    _payload.i32(value.$1);
    _payload.str(value.$2);
    _payload.u8(value.$3 ? 1 : 0);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(tupleEchoId, _payloadBytes);
    return (() { final _r = ByteReader(_bytes); return (_r.i32(), _r.str(), _r.u8() != 0); })();
  }

  Future<int> failAsync(String msg) async {
    final _payload = ByteWriter();
    _payload.str(msg);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(failAsyncId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  Stream<int> failStream(String msg) {
    final _payload = ByteWriter();
    _payload.str(msg);
    return bridge.openStream<int>(failStreamId, _payload.takeBytes(), (final _r) => _r.i32());
  }

  Future<String> downloadWithProgress(String url, StreamController<int>? progress) async {
    final _payload = ByteWriter();
    _payload.str(url);
    final _bytes = await bridge.invokeAsyncMethodWithStream<int>(downloadWithProgressId, _payload, progress, (final _r) => _r.i32());
    return ByteReader(_bytes).str();
  }

  Future<int?> maybeDouble(int? value) async {
    final _payload = ByteWriter();
    if (value == null) { _payload.u8(0); } else { _payload.u8(1);
      _payload.i32(value);
    }
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(maybeDoubleId, _payloadBytes);
    return (() { final _r = ByteReader(_bytes); final _has = _r.u8() != 0; return _has ? _r.i32() : null; })();
  }

  Future<int> add(int a, int b) async {
    final _payload = ByteWriter();
    _payload.i32(a);
    _payload.i32(b);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(addId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  int bridgeVersion() {
    final _payload = ByteWriter();
    final _payloadBytes = _payload.takeBytes();
    final _bytes = bridge.invokeSyncMethod(bridgeVersionId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  Future<int> sumArray(List<int> values) async {
    final _payload = ByteWriter();
    if (values.length != 4) throw StateError('array length mismatch');
    for (final _v in values) {
      _payload.i32(_v);
    }
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(sumArrayId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  Future<String> invokeRegistered(String input) async {
    final _payload = ByteWriter();
    _payload.str(input);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(invokeRegisteredId, _payloadBytes);
    return ByteReader(_bytes).str();
  }

  Future<int> incrementI64(int value) async {
    final _payload = ByteWriter();
    _payload.i64(value);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(incrementI64Id, _payloadBytes);
    return ByteReader(_bytes).i64();
  }

  Future<DateTime> echoTime(DateTime value) async {
    final _payload = ByteWriter();
    _payload.i64(value.microsecondsSinceEpoch);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(echoTimeId, _payloadBytes);
    return DateTime.fromMicrosecondsSinceEpoch(ByteReader(_bytes).i64(), isUtc: true);
  }

  Future<OrderStatus?> optionalStatus(OrderStatus? value) async {
    final _payload = ByteWriter();
    if (value == null) { _payload.u8(0); } else { _payload.u8(1);
      _payload.i32(value.index);
    }
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(optionalStatusId, _payloadBytes);
    return (() { final _r = ByteReader(_bytes); final _has = _r.u8() != 0; return _has ? OrderStatus.values[_r.i32()] : null; })();
  }

  Future<List<int>> echoList(List<int> values) async {
    final _payload = ByteWriter();
    _payload.u32(values.length);
    for (final _v in values) {
      _payload.i32(_v);
    }
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(echoListId, _payloadBytes);
    return (() { final _r = ByteReader(_bytes); final _n = _r.u32(); final _result = <int>[]; for (var _i = 0; _i < _n; _i++) { _result.add(_r.i32()); } return _result; })();
  }

  Future<String> invokeRegisteredAsync(String input) async {
    final _payload = ByteWriter();
    _payload.str(input);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(invokeRegisteredAsyncId, _payloadBytes);
    return ByteReader(_bytes).str();
  }

  Future<String> concatDartFn(Future<String> Function(String, String) callback, String a, String b) async {
    final _callbackWrapper = (Uint8List _argBytes) async {
      final _r = ByteReader(_argBytes);
      final _a0 = _r.str();
      final _a1 = _r.str();
      final _res = await callback(_a0, _a1);
      final _w = ByteWriter();
      _w.str(_res);
      return _w.takeBytes();
    };
    final _callbackId = bridge.registerDartFn(_callbackWrapper);
    try {
      final _payload = ByteWriter();
      _payload.u64(_callbackId);
      _payload.str(a);
      _payload.str(b);
      final _payloadBytes = _payload.takeBytes();
      final _bytes = await bridge.invokeAsyncMethod(concatDartFnId, _payloadBytes);
      return ByteReader(_bytes).str();
    } finally {
      bridge.unregisterDartFn(_callbackId);
    }
  }

  Future<Point> scale(Point p, double factor) async {
    final _payload = ByteWriter();
    _writeDataClass_Point(_payload, p);
    _payload.f64(factor);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(scaleId, _payloadBytes);
    return _readDataClass_Point(ByteReader(_bytes));
  }

  Future<bool> negateBool(bool value) async {
    final _payload = ByteWriter();
    _payload.u8(value ? 1 : 0);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(negateBoolId, _payloadBytes);
    return ByteReader(_bytes).u8() != 0;
  }

  int failSync(String msg) {
    final _payload = ByteWriter();
    _payload.str(msg);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = bridge.invokeSyncMethod(failSyncId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  Future<String> sleepGreeting(String name) async {
    final _payload = ByteWriter();
    _payload.str(name);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(sleepGreetingId, _payloadBytes);
    return ByteReader(_bytes).str();
  }

  Future<BigInt> echoU128(BigInt value) async {
    final _payload = ByteWriter();
    _payload.writeU128(value);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(echoU128Id, _payloadBytes);
    return ByteReader(_bytes).readU128();
  }

  DateTime echoTimeSync(DateTime value) {
    final _payload = ByteWriter();
    _payload.i64(value.microsecondsSinceEpoch);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = bridge.invokeSyncMethod(echoTimeSyncId, _payloadBytes);
    return DateTime.fromMicrosecondsSinceEpoch(ByteReader(_bytes).i64(), isUtc: true);
  }

  Future<int> failNonStd() async {
    final _payload = ByteWriter();
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(failNonStdId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  Future<int> addCounters(Counter a, Counter b) async {
    a.ensureAlive();
    b.ensureAlive();
    final _payload = ByteWriter();
    _payload.u64(a.handle);
    _payload.u64(b.handle);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(addCountersId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  Future<int> incrementU32(int value) async {
    final _payload = ByteWriter();
    _payload.u32(value);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(incrementU32Id, _payloadBytes);
    return ByteReader(_bytes).u32();
  }

  Stream<int> tickStream(int count, int intervalMs) {
    final _payload = ByteWriter();
    _payload.i32(count);
    _payload.i32(intervalMs);
    return bridge.openStream<int>(tickStreamId, _payload.takeBytes(), (final _r) => _r.i32());
  }

  bool registerDartFn(Future<String> Function(String) callback) {
    final _callbackWrapper = (Uint8List _argBytes) async {
      final _r = ByteReader(_argBytes);
      final _a0 = _r.str();
      final _res = await callback(_a0);
      final _w = ByteWriter();
      _w.str(_res);
      return _w.takeBytes();
    };
    final _callbackId = bridge.registerDartFn(_callbackWrapper);
    try {
      final _payload = ByteWriter();
      _payload.u64(_callbackId);
      final _payloadBytes = _payload.takeBytes();
      final _bytes = bridge.invokeSyncMethod(registerDartFnId, _payloadBytes);
      return ByteReader(_bytes).u8() != 0;
    } finally {
      // BRIDGE_PERSIST: callback not unregistered; caller manages lifecycle.
    }
  }

  Future<String> greetDartFn(Future<String> Function(String) callback, String name) async {
    final _callbackWrapper = (Uint8List _argBytes) async {
      final _r = ByteReader(_argBytes);
      final _a0 = _r.str();
      final _res = await callback(_a0);
      final _w = ByteWriter();
      _w.str(_res);
      return _w.takeBytes();
    };
    final _callbackId = bridge.registerDartFn(_callbackWrapper);
    try {
      final _payload = ByteWriter();
      _payload.u64(_callbackId);
      _payload.str(name);
      final _payloadBytes = _payload.takeBytes();
      final _bytes = await bridge.invokeAsyncMethod(greetDartFnId, _payloadBytes);
      return ByteReader(_bytes).str();
    } finally {
      bridge.unregisterDartFn(_callbackId);
    }
  }

  List<List<List<int>>> nestedCube(int n) {
    final _payload = ByteWriter();
    _payload.i32(n);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = bridge.invokeSyncMethod(nestedCubeId, _payloadBytes);
    return (() { final _r = ByteReader(_bytes); final _n = _r.u32(); final _result = <List<List<int>>>[]; for (var _i = 0; _i < _n; _i++) { _result.add((() { final _n = _r.u32(); final _result = <List<int>>[]; for (var _i = 0; _i < _n; _i++) { _result.add((() { final _n = _r.u32(); final _result = <int>[]; for (var _i = 0; _i < _n; _i++) { _result.add(_r.i32()); } return _result; })()); } return _result; })()); } return _result; })();
  }

  Future<int> sumSet(Set<int> values) async {
    final _payload = ByteWriter();
    _payload.u32(values.length);
    for (final _v in values) {
      _payload.i32(_v);
    }
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(sumSetId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  Future<Rect> boundingBox(List<Point> points) async {
    final _payload = ByteWriter();
    _payload.u32(points.length);
    for (final _v in points) {
      _writeDataClass_Point(_payload, _v);
    }
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(boundingBoxId, _payloadBytes);
    return _readDataClass_Rect(ByteReader(_bytes));
  }

  int syncDartFnBlockingUs(Future<String> Function(String) callback, String input) {
    final _callbackWrapper = (Uint8List _argBytes) async {
      final _r = ByteReader(_argBytes);
      final _a0 = _r.str();
      final _res = await callback(_a0);
      final _w = ByteWriter();
      _w.str(_res);
      return _w.takeBytes();
    };
    final _callbackId = bridge.registerDartFn(_callbackWrapper);
    try {
      final _payload = ByteWriter();
      _payload.u64(_callbackId);
      _payload.str(input);
      final _payloadBytes = _payload.takeBytes();
      final _bytes = bridge.invokeSyncMethod(syncDartFnBlockingUsId, _payloadBytes);
      return ByteReader(_bytes).i64();
    } finally {
      bridge.unregisterDartFn(_callbackId);
    }
  }

  Future<BigInt> echoI128(BigInt value) async {
    final _payload = ByteWriter();
    _payload.writeI128(value);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(echoI128Id, _payloadBytes);
    return ByteReader(_bytes).readI128();
  }

  Future<String?> optionalString(String? value) async {
    final _payload = ByteWriter();
    if (value == null) { _payload.u8(0); } else { _payload.u8(1);
      _payload.str(value);
    }
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(optionalStringId, _payloadBytes);
    return (() { final _r = ByteReader(_bytes); final _has = _r.u8() != 0; return _has ? _r.str() : null; })();
  }

  Future<OrderStatus> nextStatus(OrderStatus current) async {
    final _payload = ByteWriter();
    _payload.i32(current.index);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(nextStatusId, _payloadBytes);
    return OrderStatus.values[ByteReader(_bytes).i32()];
  }

  Counter counterNewWithInitialValue(int initialValue) {
    final _payload = ByteWriter();
    _payload.i32(initialValue);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = bridge.invokeSyncMethod(counterNewWithInitialValueId, _payloadBytes);
    return Counter.fromHandle(bridge: bridge, handle: ByteReader(_bytes).u64());
  }

  Counter counterNew() {
    final _payload = ByteWriter();
    final _payloadBytes = _payload.takeBytes();
    final _bytes = bridge.invokeSyncMethod(counterNewId, _payloadBytes);
    return Counter.fromHandle(bridge: bridge, handle: ByteReader(_bytes).u64());
  }

  Future<int> counterValue(Counter self) async {
    self.ensureAlive();
    final _payload = ByteWriter();
    _payload.u64(self.handle);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(counterValueId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  int counterValueSync(Counter self) {
    self.ensureAlive();
    final _payload = ByteWriter();
    _payload.u64(self.handle);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = bridge.invokeSyncMethod(counterValueSyncId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  String counterToString(Counter self) {
    self.ensureAlive();
    final _payload = ByteWriter();
    _payload.u64(self.handle);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = bridge.invokeSyncMethod(counterToStringId, _payloadBytes);
    return ByteReader(_bytes).str();
  }

  Future<void> counterIncrement(Counter self, int delta) async {
    self.ensureAlive();
    final _payload = ByteWriter();
    _payload.u64(self.handle);
    _payload.i32(delta);
    final _payloadBytes = _payload.takeBytes();
    await bridge.invokeAsyncMethod(counterIncrementId, _payloadBytes);
  }

  Future<int> counterSleepAndGet(Counter self, int sleepMs) async {
    self.ensureAlive();
    final _payload = ByteWriter();
    _payload.u64(self.handle);
    _payload.i32(sleepMs);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(counterSleepAndGetId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  Future<int> counterAddList(Counter self, List<int> values) async {
    self.ensureAlive();
    final _payload = ByteWriter();
    _payload.u64(self.handle);
    _payload.u32(values.length);
    for (final _v in values) {
      _payload.i32(_v);
    }
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(counterAddListId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  Future<void> counterSetValue(Counter self, int? value) async {
    self.ensureAlive();
    final _payload = ByteWriter();
    _payload.u64(self.handle);
    if (value == null) { _payload.u8(0); } else { _payload.u8(1);
      _payload.i32(value!);
    }
    final _payloadBytes = _payload.takeBytes();
    await bridge.invokeAsyncMethod(counterSetValueId, _payloadBytes);
  }

  Future<Counter> counterDuplicate(Counter self) async {
    self.ensureAlive();
    final _payload = ByteWriter();
    _payload.u64(self.handle);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(counterDuplicateId, _payloadBytes);
    return Counter.fromHandle(bridge: bridge, handle: ByteReader(_bytes).u64());
  }

  Future<int> counterAddTo(Counter self, Counter other) async {
    self.ensureAlive();
    other.ensureAlive();
    final _payload = ByteWriter();
    _payload.u64(self.handle);
    _payload.u64(other.handle);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = await bridge.invokeAsyncMethod(counterAddToId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  int counterSum(int a, int b) {
    final _payload = ByteWriter();
    _payload.i32(a);
    _payload.i32(b);
    final _payloadBytes = _payload.takeBytes();
    final _bytes = bridge.invokeSyncMethod(counterSumId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }

  Future<String> counterGreetDartFn(Counter self, Future<String> Function(String) callback, String name) async {
    self.ensureAlive();
    final _callbackWrapper = (Uint8List _argBytes) async {
      final _r = ByteReader(_argBytes);
      final _a0 = _r.str();
      final _res = await callback(_a0);
      final _w = ByteWriter();
      _w.str(_res);
      return _w.takeBytes();
    };
    final _callbackId = bridge.registerDartFn(_callbackWrapper);
    try {
      final _payload = ByteWriter();
      _payload.u64(self.handle);
      _payload.u64(_callbackId);
      _payload.str(name);
      final _payloadBytes = _payload.takeBytes();
      final _bytes = await bridge.invokeAsyncMethod(counterGreetDartFnId, _payloadBytes);
      return ByteReader(_bytes).str();
    } finally {
      bridge.unregisterDartFn(_callbackId);
    }
  }

  Stream<int> counterTickStream(Counter self, int count, int intervalMs) {
    self.ensureAlive();
    final _payload = ByteWriter();
    _payload.u64(self.handle);
    _payload.i32(count);
    _payload.i32(intervalMs);
    return bridge.openStream<int>(counterTickStreamId, _payload.takeBytes(), (final _r) => _r.i32());
  }

  int counterAliveCount() {
    final _payload = ByteWriter();
    final _payloadBytes = _payload.takeBytes();
    final _bytes = bridge.invokeSyncMethod(counterAliveCountId, _payloadBytes);
    return ByteReader(_bytes).i32();
  }
}
