// GENERATED by dart_cpp_bridge codegen — do not edit.
// Source: foreign_api.h

import 'dart:async';

import '../gcm_generated.dart';

// ═════════════════════════════════════════════
// Functions
// ═════════════════════════════════════════════

Future<String> startUvWorker() => BridgeApiImpl.instance.startUvWorker();

Future<String> callDartFromUv({required Future<String> Function(String) callback, required String input}) => BridgeApiImpl.instance.callDartFromUv(callback, input);

Future<int> uvCompute({required int n}) => BridgeApiImpl.instance.uvCompute(n);

Stream<String> uvStream({int count = 5, int intervalMs = 50}) => BridgeApiImpl.instance.uvStream(count, intervalMs);

Future<String> askUv({required String message}) => BridgeApiImpl.instance.askUv(message);

Future<String> stopUvWorker() => BridgeApiImpl.instance.stopUvWorker();

// ─── cbridge 纯 C API 测试 ───

Future<String> testCbridgeAsync() => BridgeApiImpl.instance.testCbridgeAsync();

Future<String> testCbridgeAsyncFail() => BridgeApiImpl.instance.testCbridgeAsyncFail();

Future<String> testCbridgeAsyncCancel() => BridgeApiImpl.instance.testCbridgeAsyncCancel();

Future<String> testChannelService() => BridgeApiImpl.instance.testChannelService();

Future<String> testChannelServiceConcurrent() => BridgeApiImpl.instance.testChannelServiceConcurrent();

Future<String> testCbridgeInvoke({required Future<String> Function(String) callback, required String input}) => BridgeApiImpl.instance.testCbridgeInvoke(callback, input);
