// GENERATED by dart_cpp_bridge codegen — do not edit.
// Source: foreign_api.h

import '../gcm_generated.dart';

// ═════════════════════════════════════════════
// Functions
// ═════════════════════════════════════════════

Future<String> startUvWorker() =>
    BridgeApiImpl.instance.startUvWorker();

Future<int> uvCompute({required int n}) =>
    BridgeApiImpl.instance.uvCompute(n);

Stream<String> uvStream({int count = 5, int intervalMs = 50}) =>
    BridgeApiImpl.instance.uvStream(count, intervalMs);

Future<String> askUv({required String message}) =>
    BridgeApiImpl.instance.askUv(message);

Future<String> stopUvWorker() =>
    BridgeApiImpl.instance.stopUvWorker();
